config/routes.rb
Rails.application.routes.draw do
  root 'homes#top' #homesコントローラはadminとdepartmentの外にあるからこのような書き方になる

  devise_for :department, controllers: {
    sessions: "department/sessions"
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }


  # get 'search' => 'search#search'

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'items#search', as: 'search'
    #get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: [:destroy]
    resources :orders, only: [:index, :show, :update]
    resources :production, only: [:update]
    resources :departments do
      get :search, on: :collection
    end
    resources :order_details, only: [:update]
  end

  scope module: :department do
    get 'search' => 'items#search', as: 'search'
    get 'department/mypage' => 'departments#show', as: 'departmentpage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    #get 'users/information/edit' => 'users#edit', as: 'edit_information'
    #patch 'customers/information' => 'customers#update', as: 'update_information'
    #put 'customers/information' => 'customers#update'
    get 'orders/confirmation' => 'orders#confirmation'
   # post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :items, only: [:index, :show] do #do~endがここでくくられているのか理由を聞く #なぜ37行目と39行目は分けてあるのか聞く
      resource :bookmarks, only: [:create, :destroy]
      #resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:create, :update, :index, :destroy]
    #resources :cart_items, only: [:index]
    resources :orders, only: [:index, :create, :show] do
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!
    def top
      @orders = Order.all.paginate(page: params[:page], per_page: 10)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
  <h1 class="admin_top-txt">
  	注文履歴一覧
  	</h1>
  	<center>
      <table border="1">
        <tr>
          <th><center>注文日時</center></th>
          <td><center>部門名</center></td>
          <td><center>作業状況</center></td>
        </tr>
        <tr>
          <% @orders.each do |order| %>
          <th><%= link_to order.created_at.strftime("%Y年%m月%d日"), admin_order_path(order) %></th>
          <td><center><%= order.department.name %></center></td>
          <td><center><%= order.status_i18n %></center></td>
        </tr>
  	<% end %>
  	  </table>
  	  </center><br><br>
  <%= will_paginate(@orders, class: "pagination justify-content-center",renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</section>