config/routes.rb
Rails.application.routes.draw do
  root 'homes#top' #homesコントローラはadminとdepartmentの外にあるからこのような書き方になる

  devise_for :department, controllers: {
    sessions: "department/sessions"
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }


  # get 'search' => 'search#search'

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'items#search', as: 'search'
    #get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: [:destroy]
    resources :orders, only: [:index, :show, :update]
    resources :production, only: [:update]
    resources :departments do
      get :search, on: :collection
    end
    resources :order_details, only: [:update]
  end

  scope module: :department do
    get 'search' => 'items#search', as: 'search'
    get 'department/mypage' => 'departments#show', as: 'departmentpage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    #get 'users/information/edit' => 'users#edit', as: 'edit_information'
    #patch 'customers/information' => 'customers#update', as: 'update_information'
    #put 'customers/information' => 'customers#update'
    get 'orders/confirmation' => 'orders#confirmation'
   # post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :items, only: [:index, :show] do #do~endがここでくくられているのか理由を聞く #なぜ37行目と39行目は分けてあるのか聞く
      resource :bookmarks, only: [:create, :destroy]
      #resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:create, :update, :index, :destroy]
    #resources :cart_items, only: [:index]
    resources :orders, only: [:index, :create, :show] do
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :department
  has_many :order_details

  validates :delivery_department, inclusion: { in: ['1階南棟', '1階北棟', '2階南棟', '2階北棟'] }
  enum status: {accepting: 0, preparing_for_delivery: 1, delivered: 2, cannot_start: 99}

end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < ApplicationController
  before_action :authenticate_admin!
  def top
  end

  def new
   @department = Department.new
  end

  def create
    @department = Department.new(department_params)
    if @department.save
    redirect_to admin_department_path(@department.id)
    else
     #@books=Book.all
     #@user=current_user

    render :index
    end
  end

  def index
    #@departments = Department.all.order(:department_number)
    @departments = Department.all.order(:department_number).paginate(page: params[:page], per_page: 6)
  end

  def show

    @department = Department.find(params[:id])
  end

  def edit
    @department =  Department.find(params[:id])
  end

  def update
    @department =  Department.find(params[:id])
    if
     @department.update(depart_params)
     redirect_to admin_department_path(@department)
    else
     render :edit
    end
  end

  def destroy
    department = Department.find(params[:id])  # データ（レコード）を1件取得
    department.destroy# データ（レコード）を削除
    redirect_to admin_department_index_path  # 投稿一覧画面へリダイレクト
  end

  def search
    @departments = Department.search(params[:keyword]).paginate(page: params[:page], per_page: 6)
    @keyword = params[:keyword]
    render "index"
  end

  private

    def department_params
      params.require(:department).permit(:name, :department_number, :password)
    end
  
    def depart_params
      params.require(:department).permit(:name, :department_number)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_order, only: [:show, :update]

  def index
    if params[:department_id]
      @customer = Customer.find(params[:department_id])
      @orders = @customer.orders.page(params[:page]).reverse_order
    elsif params[:created_at] == "today"
      @orders = Order.ordered_today.includes(:department).page(params[:page]).reverse_order
    else
      @orders = Order.includes(:department).page(params[:page]).reverse_order
    end
  end

  def show
    @order_details = @order.order_details.includes(:item)
    @department = @order.department
  end

  def update
    if @order.update(order_params) && @order.confirm_deposit?
      @order.order_details.update_all(making_status: 0)
    end
    redirect_to admin_order_path(@order)
  end


  private

    def order_params
      params.require(:order_detail).permit(:status)
    end
  
    def ensure_order
      @order = Order.find(params[:id])
    end
end

app/controllers/department/bookmarks_controller.rb
class Department::BookmarksController < ApplicationController
   def create
    @item = Item.find(params[:item_id])
    bookmark = @item.bookmarks.new(department_id: current_department.id)
    if bookmark.save
      redirect_to request.referer
    else
      redirect_to request.referer
    end
   end

   def destroy
    @item = Item.find(params[:item_id])
    bookmark = @item.bookmarks.find_by(department_id: current_department.id)
    if bookmark.present?
        bookmark.destroy
        redirect_to request.referer
    else
        redirect_to request.referer
    end
   end
end

app/controllers/department/cart_items_controller.rb
class Department::CartItemsController < ApplicationController
 before_action :authenticate_department!
 before_action :set_cart_item, only: [:update, :destroy]

  def index
    @cart_items = current_department.cart_items
  end

  def create
    @item = Item.find(params[:cart_item][:item_id])
    @cart_items = current_department.cart_items
    if current_department.cart_items.where(item_id: @item.id).present?
      print('=================')
      @cart_item = current_department.cart_items.find_by(item_id: @item.id)
      new_amount = @cart_item.amount + cart_item_params[:amount].to_i
      if @item.amount < new_amount
        print(1111111111)
        redirect_back  fallback_location: root_path, alert: "在庫が足りません"
      else
        @cart_item.update(amount: new_amount)
        print(@cart_item)
        redirect_to cart_items_path
      end
    else
      print('-----------------')
      print(@item.amount)
      print(cart_item_params[:amount].to_i)
      if @item.amount >= cart_item_params[:amount].to_i
        print(22222222222)
        # カートにアイテムを追加する
        @cart_item = current_department.cart_items.new(cart_item_params)
        @cart_item.item_id = @item.id
        if @cart_item.save
          redirect_to cart_items_path
        else
          render 'departments/items/show'
        end
      else
        redirect_back fallback_location: root_path, alert: "在庫が足りません"
      end
    end
  end

  def update
    @cart_item.update(cart_item_params) if @cart_item
    redirect_to cart_items_path
  end

  def destroy
    @cart_item.destroy if @cart_item
    redirect_to cart_items_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:amount)
  end

  def set_cart_item
   @cart_item = CartItem.find(params[:id])
  end
end

app/controllers/department/confirmations_controller.rb
# frozen_string_literal: true

class Department::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/department/departments_controller.rb
class Department::DepartmentsController < ApplicationController
  before_action :authenticate_department!
  before_action :set_current_department

  def show
    @bookmarks = Bookmark.where(department_id: current_department.id)
  end

  def edit
  end

  private

  def set_current_department
    @department = current_department
  end

end

app/controllers/department/items_controller.rb
class Department::ItemsController < ApplicationController
  def index
    @items = Item.all.paginate(page: params[:page], per_page: 7)
  end


   def search
    @items = Item.search(params[:keyword]).paginate(page: params[:page], per_page: 7)
    @keyword = params[:keyword]
    render "index"
   end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

end

app/controllers/department/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Department::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/department/orders_controller.rb
class Department::OrdersController < ApplicationController
   before_action :authenticate_department!

  def new
    @order = Order.new
  end

  def confirmation
    @cart_items = current_department.cart_items
    @order = Order.new
  end

  def error
  end

  def create
    @not_order_item = []
    @order = current_department.orders.new(order_params)
    if @order.save
      # @order.create_order_details(current_department)
      current_department.cart_items.each do |item|
        target_item = Item.find(item.item_id)
        if item.amount <= target_item.amount
        OrderDetail.create!([
            order_id: @order.id,
            item_id: item.item_id,
            amount: item.amount
          ])

         if target_item
          target_item.amount = target_item.amount - item.amount
          if target_item.amount == 0
             target_item.is_active = false
          end
          target_item.save!
         end
        else
         OrderDetail.create!([
            order_id: @order.id,
            item_id: item.item_id,
            amount: item.amount,
            making_status: 99
          ])
          @order.cannot_start!
          @not_order_item.push(target_item)
        end

      end

      current_department.cart_items.destroy_all
    
      render :thanks
    else
      @cart_items = current_department.cart_items
      render :confirmation
    end
    
  end

  def thanks
  end

  def index
    @orders = current_department.orders
  end

  def show
    @order = current_department.orders.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:delivery_department)
  end

end

app/controllers/department/passwords_controller.rb
# frozen_string_literal: true

class Department::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/department/registrations_controller.rb
# frozen_string_literal: true

class Department::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/department/sessions_controller.rb
# frozen_string_literal: true

class Department::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:department_number])
   end
  def after_sign_in_path_for(resource)
    departmentpage_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/department/unlocks_controller.rb
# frozen_string_literal: true

class Department::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/departments/confirmations_controller.rb
# frozen_string_literal: true

class Departments::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/departments/passwords_controller.rb
# frozen_string_literal: true

class Departments::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/departments/registrations_controller.rb
# frozen_string_literal: true

class Departments::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/views/department/orders/confirmation.html.erb
<section class="inner">
	<h1 class="section-ttl">注文情報確認</h1>
	<center>
		<table border="1">
			<thead>
				<tr>
					<th><center>部品名</center></th>
					<th><center>数量</center></th>
				</tr>
			</thead>
			<tbody>
				<% @cart_items.each do |cart_item| %>
					<% item = cart_item.item %>
					<tr>
						<td>
							<%= image_tag item.image, size: "100x100" %><br>
						  <center><%= item.name %></center></td>
						<td><center><%= cart_item.amount %></center></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<br><br>
	      <%= form_with model: @order, url: orders_path do |f| %>
		    <div class="field">
			  <label>お届け先</label>
			  <%# MODELのバリデーションのinclusionの編集も忘れずに %>
			  <%= f.select :delivery_department, ['1階南棟', '1階北棟', '2階南棟', '2階北棟'], {include_blank: 'お届け先を選択してください'} %>
		    </div>
		    <br><br>
	        <div class="actions text-center">
			  <%= link_to 'ショッピングカートに戻る',cart_items_path, class: "btn btn-success" %><br><br>
			  <%= f.submit "注文を確定する", class: "btn btn-primary submit_to_create_order" %>
		    </div>
	      <% end %>
	</center>
</section>

app/views/department/orders/index.html.erb
<section class="inner">
	<h1 class="section-ttl">注文履歴一覧</h1>
	<center>
	<table border="1">
		<thead>
			<tr>
				<th><center>注文日</center></th>
				<th><center>配送先</center></th>
				<th><center>注文商品</center></th>
				<th><center>対応状況</center></th>
				<th><center>注文詳細</center></th>
			</tr>
		</thead>
		<tbody>
			<% @orders.each do |order| %>
				<tr>
					<td><center><%= order.created_at.strftime("%Y年%m月%d日") %></center>
					<td>
						<center><%= order.delivery_department %></center>
					</td>
					<td>
						<% order.order_details.each do |order_detail| %>
						<center><%= order_detail.item.name %></center>
						<% end %>
					</td>
					<td><center><%= order.status_i18n %></center></td>
					<td><center>
						<%= link_to "表示する", order_path(order), class: "btn btn-primary" %>
						</center>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table><br><br>
    <%= link_to '戻る', departmentpage_path, class: "btn btn-success" %>
</center>
</section>

app/views/department/orders/show.html.erb
<section class="inner">
	<h1 class="section-ttl">注文履歴詳細</h1>
	<center>
		<caption class="fz18 text-left">注文情報</caption>
		<table border="1">
		<tbody>
			<tr>
				<td>注文日</td>
				<td><%= @order.created_at.strftime("%Y年%m月%d日") %></td>
			</tr>
			<tr>
				<td>配送先</td>
				<td>
					<%= @order.delivery_department %>
				</td>
			</tr>
			<tr>
				<td>対応状況</td>
				<td><%= @order.status_i18n %></td>
			</tr>
		</tbody>
    	</table><br>
      <div class="flex">
		<caption class="fz18 text-left">注文内容</caption>
		<table border="1">
			<thead>
				<tr>
					<th><center>部品ID</center></th>
					<th><center>部品名</center></th>
					<th>数量</th>
				</tr>
			</thead>
			<tbody>
				<% @order.order_details.includes(:item).each do |order_detail| %>
					<% item = order_detail.item %>
					<tr>
						<td><center><%= item.id %></center></td>
						<td><%= image_tag item.image, format: "jpeg", fallback: "no-image.png", size: "100x100" %>
						<center>
						<%= link_to item.name, item_path(item) %></td>
						<td><center><%= order_detail.amount %></center></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	  </div>
    </center><br><br>
    <% @order.order_details.includes(:item).each do |order_detail| %>
	  <% item = order_detail.item %>
		 <% if order_detail.making_status == "sold_out" %>
		   <center>
		   	<p style="color: red">売り切れで準備ができなかった部品があります。<br>
				在庫切れでもご注文は承ることが出来ておりますので再注文にはご注意ください。<br>
				その際は最長で2日間ほどお時間をいただくことがございますのでご了承下さい。</p>
			</center>
			<center>
				<table border="1">
				　<thead>
				　 <tr>
					   <th><center>部品ID</center></th>
					   <th><center>商品名</center></th>
					   <th>数量</th>
				     </tr>
			      </thead>
			      <tbody>
					<tr>
					  <td><center><%= item.id %></center></td>
					  <td>
						<%= image_tag item.image, format: "jpeg", fallback: "no-image.png", size: "100x100" %>
						<center>
						<%= link_to item.name, item_path(item) %></td>
						<td class="text-center"><%= order_detail.amount %>
						</center>
						</td>
					</tr>
		<% end %>
	<% end %>
				</td>
				</table>
				</center>

</section>

app/views/department/orders/thanks.html.erb
<section class="inner" id="thanks">
	<br>
	<div class="text-center">
		<h2 class="section-ttl">ご注文ありがとうございました！</h2><br>
		<% if !@not_order_item.nil? %>
		 <% @not_order_item.each do |item| %>
		  <p style="color: red"><%= item.name %>は在庫切れにより購入が出来ませんでした。<br>
		  なお、複数の部品をご注文の場合は在庫切れでなかった部品のみのお届けとなります。<br>
		  在庫切れでもご注文は承ることが出来ております。その際は最長で2日間ほどお時間をいただくことがございますのでご了承下さい。</p>
		 <% end %>
		<% end %>
		<%= link_to "続けて注文する", items_path, class: "btn btn-primary" %>
	</div>
</section>