config/routes.rb
Rails.application.routes.draw do
  root 'homes#top' #homesコントローラはadminとdepartmentの外にあるからこのような書き方になる

  devise_for :department, controllers: {
    sessions: "department/sessions"
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }


  # get 'search' => 'search#search'

  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'items#search', as: 'search'
    #get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, except: [:destroy]
    resources :orders, only: [:index, :show, :update]
    resources :production, only: [:update]
    resources :departments do
      get :search, on: :collection
    end
    resources :order_details, only: [:update]
  end

  scope module: :department do
    get 'search' => 'items#search', as: 'search'
    get 'department/mypage' => 'departments#show', as: 'departmentpage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    #get 'users/information/edit' => 'users#edit', as: 'edit_information'
    #patch 'customers/information' => 'customers#update', as: 'update_information'
    #put 'customers/information' => 'customers#update'
    get 'orders/confirmation' => 'orders#confirmation'
   # post 'orders/confirm' => 'orders#confirm'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'
    resources :items, only: [:index, :show] do #do~endがここでくくられているのか理由を聞く #なぜ37行目と39行目は分けてあるのか聞く
      resource :bookmarks, only: [:create, :destroy]
      #resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:create, :update, :index, :destroy]
    #resources :cart_items, only: [:index]
    resources :orders, only: [:index, :create, :show] do
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :item
  belongs_to :department
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :department
  belongs_to :item
end

app/models/department.rb
class Department < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, authentication_keys: [:department_number]
  
  has_many :cart_items
  has_many :orders
  has_many :bookmarks
  
  def has_in_cart(item)
    cart_items.find_by(item_id: item.id)
  end
  
 def self.search(keyword)
  where(["name like?", "%#{keyword}%"])
 end
end

app/models/item.rb
class Item < ApplicationRecord
 has_one_attached :image
 #has_one_attached :カラム名
  has_many :cart_items
  has_many :order_details
  has_many :bookmarks
 def self.search(keyword)
  where(["name like?", "%#{keyword}%"])
 end
 def bookmarked_by?(department)
    bookmarks.where(department_id: department).exists?
   
    #bookmarks.exists?(department_id: department)
 end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :department
  has_many :order_details

  validates :delivery_department, inclusion: { in: ['1階南棟', '1階北棟', '2階南棟', '2階北棟'] }
  enum status: {accepting: 0, preparing_for_delivery: 1, delivered: 2, cannot_start: 99}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { before_start: 0, pikking: 1, completed: 2 ,deal_closed: 3, sold_out: 99}
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!
    def top
      @orders = Order.all.paginate(page: params[:page], per_page: 10)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/user/items_controller.rb
class User::ItemsController < ApplicationController
   def index

     @items = Item.all
   end

   def search
    @items = Item.search(params[:keyword])
    @keyword = params[:keyword]
    render "index"
   end

  def show
    @item = Item.where_genre_active.find(params[:id])
    @cart_item = CartItem.new
  end
end

app/helpers/admin/departments_helper.rb
module Admin::DepartmentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/productions_helper.rb
module Admin::ProductionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alignment(department_number)
    format("%06<number>d", number: department_number)
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buhinnkyouyuu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag asset_path('sp.png'), size:"50x50" %> <%#画像入れたいときのコードの書き方%>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
           <li><%= link_to admin_departments_path,class: "nav-link text-light" do %>
             <i class="fas fa-home fa-w-18"></i>
             部門一覧
             <% end %>
            </li>
            <li><%= link_to admin_items_path,class: "nav-link text-light" do %>
             <i class="fas fa-cogs"></i>
             部品一覧
             <% end %>
            </li>
            <li><%= link_to admin_top_path,class: "nav-link text-light" do %>
             <i class="fas fa-history"></i>
           注文履歴一覧
           　<% end %>
          　</li>
            <li><%= link_to destroy_admin_session_path, method: :delete,class: "nav-link text-light" do %>
            <i class="fas fa-sign-out-alt"></i>
            ログアウト
            <% end %>
            </li>
          <% elsif department_signed_in? %>
            <li><%= link_to departmentpage_path,class: "nav-link text-light" do %>
               <i class="fas fa-home fa-w-18"></i>
              部門ページ
              <% end %>
            </li>
            <li><%= link_to items_path,class: "nav-link text-light" do %>
             <i class="fas fa-cogs"></i>
             部品一覧
             <% end %>
            </li>
            <li><%= link_to cart_items_path,class: "nav-link text-light" do %>
             <i class="fas fa-shopping-cart"></i>
             カート
             <% end %>
            </li>
            <li><%= link_to destroy_department_session_path, method: :delete,class: "nav-link text-light" do %>
            <i class="fas fa-sign-out-alt"></i>
            ログアウト
            <% end %>
            </li>
          <% else %>
            <li><%= link_to new_department_session_path,class: "nav-link text-light" do %>
              <i class="fas fa-sign-in-alt"></i>
              ログイン
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
 <main>
   <%= yield %>
 </main>
 <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>SUNNY PLACE COMPANY</p>
    	</div>
    </div>
  </div>
 </footer>
</body>
</html>